version: '3'
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data/
  
  backend:
    build: ./
    depends_on:
      - db
      - automigrate
    ports:
      - 8000:8000
    restart: always
    command: python main.py
  
  automigrate:
    build: ./
    depends_on:
      - db
    restart: no
    command: aerich init-db; aerich migrate

volumes:
  db_volume:
