version: '3'
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data/
  backend:
    build: ./
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always

volumes:
  db_volume:
